pub enum Tags {
    TaxInvoiceBulk,
    TIN,
    ListOfTaxInvoice,
    TaxInvoice,
    TaxInvoiceDate,
    TaxInvoiceOpt,
    TrxCode,
    AddInfo,
    CustomDoc,
    RefDesc,
    FacilityStamp,
    SellerIDTKU,
    BuyerTin,
    BuyerDocument,
    BuyerCountry,
    BuyerDocumentNumber,
    BuyerName,
    BuyerAddress,
    BuyerEmail,
    BuyerIDTKU,
    ListOfGoodService,
    GoodService,
    Opt,
    Code,
    Name,
    Unit,
    Price,
    Qty,
    TotalDiscount,
    TaxBase,
    OtherTaxBase,
    VATRate,
    VAT,
    STLGRate,
    STLG,
}

impl Tags {
    pub fn as_hierarchical_str(&self) -> &'static str {
        match self {
            Tags::TaxInvoiceBulk => "TaxInvoiceBulk",
            Tags::TIN => "TaxInvoiceBulk.TIN",
            Tags::ListOfTaxInvoice => "TaxInvoiceBulk.ListOfTaxInvoice",
            Tags::TaxInvoice => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice",
            Tags::TaxInvoiceDate => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.TaxInvoiceDate",
            Tags::TaxInvoiceOpt => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.TaxInvoiceOpt",
            Tags::TrxCode => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.TrxCode",
            Tags::AddInfo => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.AddInfo",
            Tags::CustomDoc => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.CustomDoc",
            Tags::RefDesc => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.RefDesc",
            Tags::FacilityStamp => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.FacilityStamp",
            Tags::SellerIDTKU => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.SellerIDTKU",
            Tags::BuyerTin => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.BuyerTin",
            Tags::BuyerDocument => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.BuyerDocument",
            Tags::BuyerCountry => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.BuyerCountry",
            Tags::BuyerDocumentNumber => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.BuyerDocumentNumber",
            Tags::BuyerName => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.BuyerName",
            Tags::BuyerAddress => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.BuyerAddress",
            Tags::BuyerEmail => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.BuyerEmail",
            Tags::BuyerIDTKU => "TaxInvoiceBulk.ListOfTaxInvoice.TaxInvoice.BuyerIDTKU",
            Tags::ListOfGoodService => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService",
            Tags::GoodService => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService",
            Tags::Opt => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.Opt",
            Tags::Code => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.Code",
            Tags::Name => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.Name",
            Tags::Unit => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.Unit",
            Tags::Price => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.Price",
            Tags::Qty => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.Qty",
            Tags::TotalDiscount => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.TotalDiscount",
            Tags::TaxBase => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.TaxBase",
            Tags::OtherTaxBase => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.OtherTaxBase",
            Tags::VATRate => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.VATRate",
            Tags::VAT => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.VAT",
            Tags::STLGRate => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.STLGRate",
            Tags::STLG => "TaxInvoiceBulk.ListOfTaxInvoice.ListOfGoodService.GoodService.STLG",
        }
    }

    pub fn as_literal_str(&self) -> &'static str {
        match self {
            Tags::TaxInvoiceBulk => "TaxInvoiceBulk",
            Tags::TIN => "TIN",
            Tags::ListOfTaxInvoice => "ListOfTaxInvoice",
            Tags::TaxInvoice => "TaxInvoice",
            Tags::TaxInvoiceDate => "TaxInvoiceDate",
            Tags::TaxInvoiceOpt => "TaxInvoiceOpt",
            Tags::TrxCode => "TrxCode",
            Tags::AddInfo => "AddInfo",
            Tags::CustomDoc => "CustomDoc",
            Tags::RefDesc => "RefDesc",
            Tags::FacilityStamp => "FacilityStamp",
            Tags::SellerIDTKU => "SellerIDTKU",
            Tags::BuyerTin => "BuyerTin",
            Tags::BuyerDocument => "BuyerDocument",
            Tags::BuyerCountry => "BuyerCountry",
            Tags::BuyerDocumentNumber => "BuyerDocumentNumber",
            Tags::BuyerName => "BuyerName",
            Tags::BuyerAddress => "BuyerAddress",
            Tags::BuyerEmail => "BuyerEmail",
            Tags::BuyerIDTKU => "BuyerIDTKU",
            Tags::ListOfGoodService => "ListOfGoodService",
            Tags::GoodService => "GoodService",
            Tags::Opt => "Opt",
            Tags::Code => "Code",
            Tags::Name => "Name",
            Tags::Unit => "Unit",
            Tags::Price => "Price",
            Tags::Qty => "Qty",
            Tags::TotalDiscount => "TotalDiscount",
            Tags::TaxBase => "TaxBase",
            Tags::OtherTaxBase => "OtherTaxBase",
            Tags::VATRate => "VATRate",
            Tags::VAT => "VAT",
            Tags::STLGRate => "STLGRate",
            Tags::STLG => "STLG",
        }
    }

    pub const MAPPABLE: &'static [Tags] = &[
        Tags::TaxInvoiceDate,
        Tags::TaxInvoiceOpt,
        Tags::TrxCode,
        Tags::AddInfo,
        Tags::CustomDoc,
        Tags::RefDesc,
        Tags::FacilityStamp,
        Tags::SellerIDTKU,
        Tags::BuyerTin,
        Tags::BuyerDocument,
        Tags::BuyerCountry,
        Tags::BuyerName,
        Tags::BuyerAddress,
        Tags::BuyerEmail,
        Tags::BuyerIDTKU,
        Tags::Opt,
        Tags::Code,
        Tags::Name,
        Tags::Unit,
        Tags::Price,
        Tags::Qty,
        Tags::TotalDiscount,
        Tags::TaxBase,
        Tags::OtherTaxBase,
        Tags::VATRate,
        Tags::VAT,
        Tags::STLGRate,
        Tags::STLG
    ];
}